!includeurl https://raw.githubusercontent.com/gkatsikas/hypo-workflows/refs/heads/main/palette/hypo-palette.puml
!includeurl https://raw.githubusercontent.com/gkatsikas/hypo-workflows/refs/heads/main/theme/hypo-theme.puml

' =======================
' ETSI HypO Stakeholders
' =======================

' Better add them on demand in the workflow
' actor "Infra.\nProvider" as InfPrv #000000
' actor "Vertical\nEnd User" as VertEndUser #000000
' actor "Service\nProvider" as SvcPrv #000000
' actor "Platform\nAdmin" as PltAdmin #000000

' =======================
' ETSI HypO Components
' =======================

HYPO_LOGO_BOX()

    HYPO_BOX("Portal")
        participant Web as Web
        participant Cart as Cart
    END_HYPO_BOX()

    HYPO_BOX("API")
        participant TMF as TMF
        participant Peering as Peering
        participant Registry as Registry
        participant Fabric as Fabric
    END_HYPO_BOX()

    HYPO_BUS("Service\nBus")

    HYPO_BOX("Authentication")
        participant "Authentication" as Auth_Manager
    END_HYPO_BOX()

    HYPO_BOX("Orchestrator")
        participant SONATA as SONATA
    END_HYPO_BOX()

    HYPO_BOX("Databases")
        HYPO_DB("TMF\nDB")
        HYPO_DB("Secrets\nDB")
    END_HYPO_BOX()

    HYPO_BOX("Service-Manager")
        participant "Package\nManager" as Pkg_Manager
        participant "Service\nMonitor" as Svc_Monitor
    END_HYPO_BOX()

    HYPO_BOX("Telemetry")
        participant "Telemetry" as Tel_Manager
    END_HYPO_BOX()

    HYPO_BOX("Clients")
        participant "OSS\nClient" as OSS_Client
        participant "Telemetry\nClient" as Telemetry_Client
        FABRIC_CLIENT("Fabric Client\nHypO")
    END_HYPO_BOX()

END_HYPO_LOGO_BOX()

FABRIC_BOX_LOGO("Zero-Trust\nNetwork Fabric")
    FABRIC_CTRL("Fabric\nController")
END_FABRIC_BOX()

REMOTE_INFRA_BOX("Remote Infrastructure")
    FABRIC_CLIENT("Fabric Client\nRemote")

    OSL_LOGO_BOX()
        OSL_INST("ETSI\nOpenSlice")
    END_OSL_LOGO_BOX()

    CLUSTER_LOGO_BOX()
        CLUSTER_CTRL("Cluster\nController")
        CLUSTER_NODES("Cluster\nNode")
    END_CLUSTER_LOGO_BOX()
END_REMOTE_INFRA_BOX()
