!includeurl https://raw.githubusercontent.com/gkatsikas/hypo-workflows/refs/heads/main/palette/hypo-palette.puml

hide footbox
!pragma teoz true

' =====================
' Global Theme
' =====================
!theme hacker
' !theme sunlust
' !theme minty
' !theme bluegray

' =====================
' Global Styling
' =====================
skinparam DefaultFontSize 20
skinparam defaultTextAlignment center
skinparam BackgroundColor #F0F0F0
skinparam DefaultFontColor black

' Arrow / Message Styling
skinparam ArrowColor black
skinparam SequenceMessageFontColor black
skinparam SequenceMessageFontSize 14

' Notes / Annotations Styling
skinparam NoteBackgroundColor #FEFECE
skinparam NoteBorderColor black

' Padding
skinparam BoxPadding 10
skinparam ParticipantPadding 10

' Dummy stereotype
skinparam participant {
  BackgroundColor<<spacer>> transparent
  BorderColor<<spacer>> transparent
  FontColor<<spacer>> transparent
}

skinparam sequence {
  LifeLineBorderColor<<spacer>> transparent
  LifeLineBackgroundColor<<spacer>> transparent
}

skinparam ShowStereotype false

' Actors shall have obvious outline
skinparam actor {
    BorderColor black
}

' =====================
' Reusable Components
' =====================

!unquoted procedure HYPO_BOX($name)
box "$name" #HYPO_BOX_COLOR
!endprocedure

!unquoted procedure HYPO_BOX_WHITE_TEXT($name)
box "<color:white>$name</color>" #HYPO_BOX_COLOR
!endprocedure

!unquoted procedure END_HYPO_BOX()
end box
!endprocedure

!unquoted procedure FABRIC_BOX($name)
box "$name" #FABRIC_BOX_COLOR
!endprocedure

!unquoted procedure END_FABRIC_BOX()
end box
!endprocedure

!unquoted procedure REMOTE_INFRA_BOX($name)
box "$name" #REMOTE_INFRA_BOX_COLOR
!endprocedure

!unquoted procedure END_REMOTE_INFRA_BOX()
end box
!endprocedure

' !unquoted procedure HYPO_SERVICE($name)
' participant "$name" #HYPO_SERVICE_COLOR
' !endprocedure

!unquoted procedure HYPO_DB($name)
database "$name" #HYPO_DB_COLOR
!endprocedure

!unquoted procedure FABRIC_CTRL($name)
skinparam participantBorderColor black
participant "$name" #FABRIC_CTRL_COLOR
!endprocedure

!unquoted procedure FABRIC_CLIENT($name)
skinparam participantBorderColor HYPO_BLUE_1
participant "Fabric Client\n$name" #FABRIC_CLIENT_COLOR
!endprocedure

!unquoted procedure CLUSTER_CTRL($name)
skinparam collectionsBorderColor black
collections "$name" #CLUSTER_CTRL_COLOR
!endprocedure

!unquoted procedure CLUSTER_NODES($name)
skinparam collectionsBorderColor black
collections "$name" #CLUSTER_NODES_COLOR
!endprocedure

!unquoted procedure OSL_INST($name)
skinparam participantBorderColor DarkOrange
participant "$name" #OSL_COLOR
!endprocedure

